In [2]:
import numpy as np 
import pandas as pd
from __future__ import division
import sklearn


In [29]:
df = pd.DataFrame()
df = pd.read_csv('/Users/rorymurray/Desktop/beer_trainingC.csv',sep = ';')

testdf = pd.DataFrame()
testdf = pd.read_csv('/Users/rorymurray/Desktop/beer_testC.csv',sep = ';')

In [7]:
df.head()

Calorific_value  Nitrogen  Turbidity  Style   Alcohol  Sugars  Bitterness  \
0        45.305310  0.459548    1.917273   ale  4.227692   16.67   12.568947   
1        43.889381  0.548977    3.186364   ale  4.289231   16.73   14.974000   
2        41.588496  0.542847    1.568182   ale  4.344615   16.48   11.848789   
3        44.553097  0.480301    1.871818   ale  4.424615   18.59   13.879632   
4        41.013274  0.441860    2.345455   ale  4.264615   16.35   12.186053   

   Beer_ID  Colour  Degree of Fermentation  
0      167   11.04               62.178571  
1      128   13.44               63.032857  
2       88   14.04               63.468571  
3      147   12.48               63.531429  
4       74   12.12               63.747143

In [30]:
x = df.iloc[:,[0,1,2,4,5,6,8,9]]
xlabels = df.iloc[:,3].values

y = testdf.iloc[:,[0,1,2,4,5,6,8,9]]
ylabels = testdf.iloc[:,3].values

print(ylabels)

['ale' 'ale' 'ale' 'ale' 'ale' 'ale' 'ale' 'ale' 'ale' 'ale' 'lager'
 'lager' 'lager' 'lager' 'lager' 'lager' 'lager' 'lager' 'lager' 'lager'
 'stout' 'stout' 'stout' 'stout' 'stout' 'stout' 'stout' 'stout' 'stout'
 'stout']


In [31]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x = sc.fit_transform(x)
y = sc.transform(y)

In [44]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=7, random_state=0,criterion = 'entropy')

# Train the Classifier to take the training features and learn how they relate
# to the training y (the species)
clf.fit(x, xlabels)



RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=7, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [45]:
prediction = clf.predict(y)
print(prediction)

['ale' 'ale' 'ale' 'ale' 'ale' 'ale' 'ale' 'ale' 'ale' 'ale' 'lager'
 'lager' 'lager' 'lager' 'lager' 'stout' 'lager' 'lager' 'lager' 'lager'
 'stout' 'lager' 'stout' 'stout' 'stout' 'stout' 'stout' 'stout' 'stout'
 'stout']


In [46]:
length = len(prediction)
score = 0


for i in range(0,len(prediction)):
    if prediction[i] == ylabels[i]:
            score += 1
            
accuracy = score/length

print(accuracy)
            

0.933333333333


In [56]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(ylabels,prediction))
print(classification_report(ylabels,prediction))
print(accuracy_score(ylabels,prediction))

[[ 9  0  1]
 [ 0 10  0]
 [ 0  0 10]]
             precision    recall  f1-score   support

        ale       1.00      0.90      0.95        10
      lager       1.00      1.00      1.00        10
      stout       0.91      1.00      0.95        10

avg / total       0.97      0.97      0.97        30

0.9666666666666667
